### PR TITLE
Fix for useLocationChange calling setter on mount

### LINKED ISSUE #86: useLocationChange is called on mount
Hi @kyeotic!

We have just upgraded `raviger` from version `1.6.0` to version `2.0.2` and we are facing a problem with a new behaviour introduced in `2.0.0` in `useLocationChange`.

`useLocationChange` will now call its callback argument on mount due to this `useLayoutEffect`:
https://github.com/kyeotic/raviger/blob/74e3b87eaf108d0950ab09f368f1f91f23345dcb/src/path.js#L93-L98

Is that completely intended? Or should that be a layout effect that only gets executed after the initial mount?

Our use case for `useLocationChange` is within modals that we want to close when the user hits the Back/Forward browser history buttons:
```jsx
// close the modal when the path has changed
useLocationChange(onClose);
```

With `2.0.2`, this code gets executed when the modal is mounted and thus it closes instantly.

### PR DESCRIPTION
**Pull request by yenoiwesa**
Fixes #86

### CODE REVIEW

**Comment by yenoiwesa** [comment]
Are these builds working?

**Comment by kyeotic** [comment]
Yes, you have a test failure

```
FAIL test/router.spec.js
  ● useRoutes › with basePath › nested router with basePath matches after navigation

    expect(element).toHaveTextContent()

    Expected element to have text content:
      2
    Received:
      Not Found

      262 | 
      263 |       act(() => navigate('/app/2/settings'))
    > 264 |       expect(getByTestId('label')).toHaveTextContent('2')
          |                                    ^
      265 |     })
      266 |   })
      267 | })

      at Object.toHaveTextContent (test/router.spec.js:264:36)
      ```

**Comment by yenoiwesa** [comment]
Yeah right sorry I was running focused tests on the path file and didn't re-run on the whole suite before submitting.

Seems that the navigate hook expects the behaviour that I am trying to patch so that won't do.

**Comment by kyeotic** [comment]
Yeah, but its not relying on `useLocationChange` doing it, its relying on [`useRoutes`](https://github.com/kyeotic/raviger/blob/master/test/router.spec.js#L233)

**Comment by kyeotic** [comment]
closing in favor of #89

**Comment by yenoiwesa** [comment]
I am so sorry about the delay @kyeotic I intended to come back to this pull request and investigate the test failure but I have been swamped by higher priority work :-(

**Comment by kyeotic** [comment]
No worries at all, I really appreciated you putting this together and I ended up keeping the test you wrote. Thank you again 🥂

**Pull request closed without merging**
