### PR TITLE
add usePathParams and useMatch

### PR DESCRIPTION
**Pull request by kyeotic**
This is a feature preview for #107. It adds the following hooks

```ts
interface PathParamOptions {
  basePath?: string
  matchTrailingSlash?: boolean
}

function usePathParams<T extends Record<string, unknown>>(
  routes: string | string[],
  options?: PathParamOption
): [string, T] | [null, null]

function useMatch(routes: string | string[], options?: PathParamOptions): string | null
```

This allows components to get path-matching information. Unlike `useRoutes` which is intended to render children based on the route these hooks simply return information about the match, or `null` of a match was not found.

Both hooks operate in two modes: a single path or an array of paths.

**useMatch** returns either a `boolean` in single path mode, or the route `string` in array mode.
**usePathParams** in single path mode returns an array of `[didMatch, props]` and in array mode it returns an array of `[routePath, props]`

### CODE REVIEW

**Comment by kyeotic** [comment]
This has been published as a beta. To try it out

```
npm i raviger@beta
// OR 
npm i raviger@2.6.0-0
```

**Comment by kyeotic** [comment]
@kristiandupont I think the overloaded return might still be a mistake. A boolean is only arguably more useful than a `string | null` even if that string is the value that was provided as input.

Do you have any thoughts on using the array-path result for both modes?

**Comment by kyeotic** [comment]
I've published a new beta with that uses the same return values for single or array inputs. I haven't updated the docs yet, im in a rush, I will get to those later today.

```
npm i raviger@beta
// OR 
npm i raviger@2.6.0-1
```

**Comment by kristiandupont** [comment]
Cool, that would be my intuition as well!

**Comment by kristiandupont** [comment]
I will, thank you Tim!

**Pull request merged**
