### PR TITLE
Fix TS declaration of useNavigationPrompt function

### PR DESCRIPTION
**Pull request by mentaljam**
Fix TypeScript error 2371

### CODE REVIEW

**Comment by kyeotic** [comment]
hey @mentaljam :wave:

Thank you for taking the time to make a PR! Before I merge this I want to understand what the issue is. Does the current declaration produce an error? If so, can you provide it.

My understanding is that [this is the correct way to declare default parameters](https://www.typescriptlang.org/docs/handbook/functions.html#optional-and-default-parameters)

**Comment by mentaljam** [comment]
Hi,

Sorry for being terse. Here is the error for tsc v3.8.3:

```sh
node_modules/raviger/types/raviger.d.ts:80:37 - error TS2371: A parameter initializer is only allowed in a function or constructor implementation.

80 export function useNavigationPrompt(predicate = true, prompt?: string): void
```

This is really a correct way to provide default parameters but not in declaration files. Also look at the second parameter: [the implementation](https://github.com/kyeotic/raviger/blob/23db7d7c98e676962b77f5aeac331e14e188864a/src/navigate.js#L26) has a default value for it but in `.d.ts` you already declared it as an optional parameter. The first parameter should be declared in the same way.

**Comment by kyeotic** [comment]
Thank you for the explanation, that makes perfect sense :)

**Comment by kyeotic** [comment]
released: https://github.com/kyeotic/raviger/releases/tag/v1.4.3

**Pull request merged**
