### PR TITLE
Make basePathMatcher case insensitive

### PR DESCRIPTION
**Pull request by micmcg**
Resolves https://github.com/kyeotic/raviger/issues/58

### CODE REVIEW

**Comment by kyeotic** [comment]
There is definitely a use case here, and I want to support this. Unfortunately this would be a breaking change as-is, as it will change the default matching behavior for everyone.

This PR needs two changes:

1. A unit test to verify that case-insentive matching happens
2. A `default=false` parameter that enables this behavior

**Comment by kyeotic** [comment]
If you don't want to tackle that I will have some time tomorrow.

**Comment by micmcg** [comment]
I'm afraid I am off sick & looking after a sick kid today, so I won't have time to get to this today sorry.

**Comment by kyeotic** [comment]
@micmcg Sorry this took me so long to get to. When I went to write the tests I discovered that this case sensitivity only exists for basePath routes, the standard routes in `useRoutes` already have case-insensitivity.

Which makes this a bug! This means we can fix it without the `default=false` option or any of the headaches of passing that config around. I will be releasing this under `1.4.4`

**Pull request closed without merging**
