### PR TITLE
V3

### PR DESCRIPTION
**Pull request by kyeotic**
This PR will track the work for releasing v3. This release is driven by bad matching of path parts that include encoded characters.

For example, prior to this fix the following would fail to match

```js
// pathname = /weird%20(route)
useRoutes({
  '/weird (route)': true
})
```

It is undesirable to require the keys passed to `useRoutes` to be uri-encoded. It has a pair of breaking changes to redress this:

### Changed
- **BREAKING**:`usePath` returns `decodeURIComponent`-ed path
- **BREAKING**:`useRoutes`, `useMatch`, and `usePathParams` match paths that have been `decodeURIComponent`-ed (e.g. `/weird (route)` will match a path of `/weird%20(route)`)

While the first is not strictly necessary I believe it is valuable to ensure that these two closely related functions behave similarly. Critically: calling `usePath()` and providing its result to a key in `useRoutes`, while a strange thing to do, should produce a matching route. 

Additional changes
### Changed
- **BREAKING**: type `RouteParams` renamed to `Routes`
- **BREAKING**: `usePathParams` return type now depends on the input params. When a string it returns just the props, when an array it returns `[path, props]`
### Fixed
- `useRoutes` props type to `(params?: Record<string, string>)` from `props: any`

There is a beta available for this release

```
npm i raviger@beta
// OR
npm i raviger@3.0.0-1
```

@yenoiwesa @macku @roypearce @zoontek @kristiandupont

Testing and Feedback is greatly appreciated, as always. I will hold this in beta for at least *ONE WEEK*; longer if issues arise.

If there are any other breaking changes to the API you believe are valuable now is the perfect time to raise them.

### CODE REVIEW

**Comment by kyeotic** [comment]
Sorry for all the wacky force pushes and commit thrashing, I royally screwed up this branch after squashing its parent 🤕

**Comment by zoontek** [comment]
May I suggest some breaking changes based on our pain points with the library? 🙂

First thing: the automatic provider wrapping. In some places, we want to match not only a component, but also a config. Example:

```tsx
const match = useRoutes({
  "/foo": () => <Foo />,
  "/bar": () => <Bar />,
  "/baz": () => <Baz />,
});

// match: JSX.Element | null
// How do we know which route is matched?
```

```tsx
const match = useRoutes({
  // The returned data could be anything!
  "/foo": () => ({ element: <Foo />, useSpecialLayout: true }),
  "/bar": () => ({ element: <Bar />, useSpecialLayout: false }),
  "/baz": () => ({ element: <Baz />, useSpecialLayout: false }),
});

// match: { element: JSX.Element, useSpecialLayout: boolean } | null
// We can do more than just match and render!
```

For that, it could be nice to remove `basePath` from `useRoutes` config and export an explicit `Provider` to put at the top of our app. Then make `useRoutes` a bit stupid, by only returning the first matched result, without the need to be an element.

---

Another cool thing could be typed routes. I could make a quick proposal for this above this PR.

**Comment by zoontek** [comment]
@kyeotic This is great! I didn't know about this hook, it seems recent. `includeContexts` seems to be a good idea too.

For the typed routes, I prepared a small TS playground: https://www.typescriptlang.org/play?jsx=4#code/MYewdgzgLgBAUgZQBoFEA2BTAthssC8MARIkgHTra5REDcMA9AzOGgJ4wAWGAThjACMMwAIYBXCPwAqbAA4YEwHgEtZsAApoRbAOY8QYsABMYRkBghgA5LADWYEAHd4yGGBE4IskcAwAoPyg5fhQsNTYAJWEQHhNCKNBYgB5oFTAdGAAfNzEsIR4smAg2PJA0ABo3DAA3XgA+WgCg+RgAOXBQ8ISYoyT1ER4PCDqYQn7BrAgYDAAPKFwjKc6g7ti-GBgAfhhDIwwAM2UwDCN1mAAuGABvGABtAGkMDiOYWyeQfZhxoYBdS+-Jg8nj8YABfehMGAAWREsnkJma-GUUwkJxgUBARWUYTQyn2HCg3BYYigshJMAAFMBMCJjgVxBjQDiMPMAJRNYIwBCyXFQJJnABqIjQYn4s3mximqSOOnKZwQGG8gwxBXFCylUDSsr8I0IQpFYrm6pgAAMACRXI77XgwAASGBERlBFoVSpEKudlrA1oKUhEyjQoJNZ22t3tjsqZCj3N5ST9AcqroG7pidR+Z0u+tF0yNkq5iuTKpDd3TG0utyzGB+jUCnJQc0GwCg-UJAIg-I2Lc4OYliyKmplcs7AygU0IMeUfK7lSIDCIdTluq+I6marztytNvDRkjUc3vv9aFLWztDpMa77JvOFv3bQ8GCDZw22xut1aMBerXvf37WrBMAAMhgetNR8Zt3U4Ns+ggyp4zQOonwuYCGzArsoOnGA4IQstrnBDkWgiAx5nQiCe2NaV0iXK4zludQPzAZdCR-ClELdSZLnaMBlkiaJkhAxtwNbZNJj6Mi83NL0fS+ABGUEACoTRPdRpKQ9Q6gXM5WVGEZEQ+FxUEwHA8EaPC-H2Qwm2UcAdkkQiSQsaDCTEvsKJ0OoWI2fR7IgS47OI4T2y7DTWUuXTPlISgjNgbIwDENA0GuM5IXtPhTExQl+Cwd1gE4QcYFxN4PygKwpmAMQeD4PB2DS45ADICM4+CgcqGIiwzqBMgJUT8iwKWojZZyIS4KTYiAtPwEZWqoPAh2IBg9AMWQIEGykRrGibkEi6gZtneaxEWhhzl22QAEkjGW4aArW-TNums4dq8-bDoe065PO1btOutrbv6uaHogBgsCODA3suj7Jqi7bfoW-6noW06GFRHgIFeob3vGz6pqgSGjpho74cRpbUdB9Hwa2u6ob2-7AeOBHJCRkGJlGsGNq+rHyfOcAMAOqBHBAbnOD4Lnzn2AweAZoYrtJ77Zpxg68aMWneBhxHTvFyZJZZzHsb+uXnoVgmAeBonGY1gytfJ2Xqa5g2cDVpmSc1iH2c57nef5wWDpF8rPeUWo7dNm62dBVlGiAA

Check the `params` types in `useRoutes` 😃. It's a portion of the work of a router I worked on.

**Comment by kyeotic** [comment]
@zoontek yeah they are from the latest release.

Those string inference types are wild, I'm still trying to wrap my head around how to write them. These are awesome! I would love to include this in raviger 😄

**Comment by zoontek** [comment]
> Those string inference types are wild, I'm still trying to wrap my head around how to write them. These are awesome! I would love to include this in raviger 😄 

Feel free to do it 🙂

**Comment by zoontek** [comment]
> That type magic stops working when `JSX.Element` is used instead of the placeholder
> 
> 
> 
> image
> 
> 

Yay, you have to replace "typeof JSXElement" === "JSXElement" string literal with JSX.Element (without typeof, it's already a type)

**Comment by kyeotic** [comment]
@zoontek Ok, I think I got it working.

Heads up, I'm going to be removing `excludeProviders` and the `CustomRoutes` option from `useRoutes`. I think it overloads the hook in a bad way. I'm still considering adding a separate hook, though I haven't come up with a good name yet.

In the meantime I want to get this type-magic working for `usePathParams`. You can use it to create the custom `useRoutes` that you want.

```js
function useCustomRoutes(routes) {
  const [path, props] = usePathParams(Object.keys(routes));
  const route = path ? routes[match](props) : null
}

const routes = {
  "/foo": { element: <Foo />, useSpecialLayout: true },
  "/bar": { element: <Bar />, useSpecialLayout: false },
  "/baz": { element: <Baz />, useSpecialLayout: false },
}

function App() {
  const route = useCustomRoutes(routes)
  // path = '/foo', route = { element: <Foo />, useSpecialLayout: true }
}

```

**Comment by kyeotic** [comment]
New V3 beta released as `3.0.0-3`, cover removal of `excludeProviders` and the type magic from @zoontek

**Comment by kyeotic** [comment]
Well, no word from the Aussies. Things look stable, I'll probably push to latest on monday.

**Comment by kyeotic** [comment]
Things are looking good. I'll push to latest on Tuesday

**Comment by zoontek** [comment]
I tried to update to v3, but `excludeProviders` seems to miss in the release (`useRoutes` add the `Provider`)

**Comment by kyeotic** [comment]
@zoontek It was removed, please see [this comment](https://github.com/kyeotic/raviger/pull/109)

**Comment by zoontek** [comment]
Then the changelog is incorrect: https://github.com/kyeotic/raviger/releases/tag/v3.0.0

**Comment by kyeotic** [comment]
Ah fuck me, I'll fix that. Sorry for the confusion

**Pull request merged**
