### PR TITLE
Typescript

### LINKED ISSUE #83: convert to typescript
V3 should be written in typescript

### PR DESCRIPTION
**Pull request by kyeotic**
Convert to typescript

This is heavily based on original work by @n33pm (who has earned a Contributor 🌟 <sup id="a1">[1](#f1)</sup>) in #88
closes #83 

**Remaining issues**

* [x] sync changes since n33pm's branch
* [x] get `example` running (parcel bundles but only a blank page renders)
* [x] fix size limit check
* [x] fix tests in CI (they work locally)
* [x] remove tsdx
* [x] remove yarn

---
<b id="f1">1</b> Contributor 🌟 's cannot be exchanged for cash or used to purchase or acquire “real world” goods or services. 🌟 's have no value in any venue or application other than @kyeotic's imagination. [↩](#a1)

### CODE REVIEW

**Comment by kyeotic** [comment]
I'm getting pretty frustrated with tsdx. Its escape hatch is barely useable, and its defaults are... questionable.

**Comment by kyeotic** [comment]
This has been published as a beta for v3

```
npm install raviger@beta

OR

npm install raviger@3.0.0-0
```

Looking for testers: @n33pm @yenoiwesa @macku @roypearce

**Comment by n33pm** [comment]
i tried 8676d50bc98551260e651de5e1c73a7ff20f2cff



but never mind.

**Comment by kyeotic** [comment]
Yeah, sorry I could have been more clear with that comment. The lint failures were definitely caused by extra plugins I hadn't uninstalled, but that wasn't the only issue I was having with tsdx. 

I couldn't control the terser settings. Things like `keep-fnames` weren't getting applied by the override no matter what I did. The different bundles had names you could change, but if you did hardcoded referenced in tsdx would break. 

I didn't have control over the things I wanted and wasn't getting enough benefit from the defaults that they had setup. I'm sure it fits someone's pipeline, but I don't like having my hands tied that much.

**Comment by roypearce** [comment]
> Looking for testers: @n33pm @yenoiwesa @macku @roypearce

It might take me a couple days, but happy to take it for a spin. Glad to see the typescript!

**Comment by roypearce** [comment]
> > Looking for testers: @n33pm @yenoiwesa @macku @roypearce
> 
> It might take me a couple days, but happy to take it for a spin. Glad to see the typescript!

I checked it out for a couple projects, the projects using the beta made it through CI all green, so no typescript errors were raised, which is great, and all e2e tests are passing, many of which test routing. I did spot checks for the features/bug fixes I had a part in, and they're all good. Caveat, only the following are used in the projects tested:

usePath, useLocationChange, useRoutes, Link, navigate, useNavigationPrompt, useQueryParams

I looked at the type previews in VS Code (hovering over one of the functions to reveal types) and most of the ones used above have good types being exposed except for Link & to a minor extent, navigate. Nothing really wrong with the types, as they are legit for what they describe, but for Link, it's difficult to tell using those tools that it is extending an html anchor element, and right clicking > Go to type definition will go to the react forwardRef type def when LinkProps is the useful bit to discover. For navigate it's just VS Code not being helpful as the overloads are collapsed into oblivion, but at least for that one you can easily get to the full type definition and see all of them.

Really great update, thanks @kyeotic @n33pm !

**Comment by kyeotic** [comment]
Thanks for the in-depth check @roypearce.

I don't have a ton of experience with typing React components. Do you have any suggestions on how the `<Link>` type could be improved?

**Comment by roypearce** [comment]
> Thanks for the in-depth check @roypearce.
> 
> I don't have a ton of experience with typing React components. Do you have any suggestions on how the `<Link>` type could be improved?

The issue is that the function's type is derived from `forwardRef`. If instead of using `forwardRef` you just manually manage the `ref` and add the `ref` prop to `LinkProps` then the code would be simpler and you'd get a better type definition as a result. [This SO's only answer](https://stackoverflow.com/questions/58469229/react-with-typescript-generics-while-using-react-forwardref) has some (hard to read and overly complex) examples, but if I were in your position I would consider option 3 first (dead simple), then option 2 (a little bloat). Option 1 and option 4 seem like they could be problematic with upgrades to react & typescript over time.

**Comment by kyeotic** [comment]
I've added a new beta for the update `<Link>` and `<ActiveLink>` types

```
npm install raviger@beta

OR

npm install raviger@2.5.0-1
```

**Comment by roypearce** [comment]
> I've added a new beta for the updated `<Link>` and `<ActiveLink>` types
> 
> ```
> npm install raviger@beta
> 
> OR
> 
> npm install raviger@2.5.0-1
> ```

Re-ran previous steps, all good! Thanks for the type update on `Link` much more useful now.

**Comment by yenoiwesa** [comment]
@kyeotic very sorry, late to the game as usual.

I just started the `raviger` upgrade to the latest release (`2.5.2`) in our product's repo and all the Selenium tests and unit tests have passed successfully (apart for `Link` component jest snapshots that have changed).
So we'll go ahead and use the new version, we'll let you know if we find any regression.

Cheers!

**Comment by kyeotic** [comment]
@yenoiwesa What changed in the snapshots?

**Comment by yenoiwesa** [comment]
Here are the Enzyme shallow test snapshot changes we had to accept with the new version:
image

**Comment by kyeotic** [comment]
That seems like an improvement, though I'm sorry I didn't catch that in testing. Hopefully that wasn't too much heartburn for you guys

**Comment by yenoiwesa** [comment]
> Press 'U' to update all failing snapshots.
It was okay :-P And yes the new version is a lot better.

**Pull request merged**
